### ISSUE TITLE
Suggestion: Add JPEG XR comparison

### ISSUE THREAD

**Issue by saschanaz** [xooyoozoo/yolo-octo-bugfixes#2]
I just built jxrdeclib.js in my [jxrlib.js](https://github.com/saschanaz/jxrlib.js) repo. Can JPEG XR be added to the current options? I will send a pull request if you don't mind.

**Comment by xooyoozoo** [comment]
Yea I'm interested. First, I'm going to go make JXR versions of the images.

**Comment by xooyoozoo** [comment]
I had some free time, so I integrated your libjxr.js myself. I hope I didn't duplicate anything you had in-progress!

There were some trivial tweaks like doubling total memory (which seemed to help Firefox) and directly converting the wrapper to a web worker. I also ran the Lib through Closure-compiler to make the size a bit more manageable.

Lastly, have you tried building the library with O2/O3? Or maybe llvm-opts? I just wonder if it helps with speed and/or filesize. I'd try it myself, but I had issues with the Emcc makefile and haven't gotten around to debugging that yet.

**Comment by saschanaz** [comment]
Great job! I just tried -O2 optimization (which adds llvm-opts -03 by default in Emscripten) and the file is now smaller than 1MB. :D

**Comment by saschanaz** [comment]
I just pushed the result. Thank you :)

BTW, I'm afraid that Closure complier may break the asm.js grammar, which enables Firefox and Chrome to run very smoothly. Emscripten [recommends](http://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html#code-size) running Closure for non-asm.js external code, but doesn't really say anything about what occurs when Closure modifies asm.js area. Would you test the performances here?

**Comment by xooyoozoo** [comment]
It's definitely faster now on first load and from image to image. There didn't seem to be a noticeable change when running the lib through closure, but the gzipped filesize is only 2KB smaller, so the rewards probably aren't worth the risk here :).

**Comment by saschanaz** [comment]
Awesome! :+1:
